name: Build and deploy Python app to Azure Web App - surajit-hackathon

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Add this step to make startup.sh executable
      - name: Make startup script executable
        run: |
          if [ -f "startup.sh" ]; then
            chmod +x startup.sh
            echo "Made startup.sh executable"
          else
            echo "startup.sh not found"
            ls -la  # List files to help diagnose
          fi
      
      - name: List files and create deployment package
        run: |
          pwd
          ls -la
          echo "Creating deployment package..."
          zip -r deployment_package.zip ./* -x venv\*
          echo "Files in deployment package:"
          unzip -l deployment_package.zip
          
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            deployment_package.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: List downloaded files
        run: |
          pwd
          ls -la
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7AD449E721D64F18B32737B259484EE9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_889B808E80D14563A3E0B862281FB3D2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21DE3A6A14D5448FB39473B09A0D8D89 }}
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'surajit-hackathon'
          slot-name: 'Production'
          package: deployment_package.zip
